name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - "lambda/"

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest # Sets or specifies the runner
    steps:
      - uses: actions/checkouts@v2

      - name: Set Up Python # Setsup our python enviroment
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Dependencies # Installs any packages
        runs: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS Creds #sets up our AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-aceess-secret-key: { { secrets.AWS_SECRET_ACCESS_Key } }
          aws-region: eu-west-2

      - name: Deploy Lambda Fuction
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
